### ISSUE TITLE
First tools to support

### ISSUE THREAD

**Issue by Nolent** [NotANameServer/incipyt#1]
Which tools should we support firstly
@LeMinaw started [a list here](../wiki/Opt-ins,-opt-outs-for-first-version)
If anyone wants to add/change something to the list, it's here we discuss about it.

I think we should optout for `unittest` instead of `pytest`, because `unittest` is in the standard library.

**Comment by Julien00859** [comment]
I am +1 with unittest as opt-out for the same reason as Nolent : it is in the standard lib

**Comment by LeMinaw** [comment]
Pretty good point, edited!

I however continue to think supporting pytest is hi-priority.

**Comment by Julien00859** [comment]
I completely agree with you, a lot of python users do prefer the pytest framework. By sticking with what's available in the standard lib or the "de-facto" standard libs (setuptools, distutils, wheel) we ensure we'll be compatible with most user environments. I can easily imagine one who doesn't know much about the python ecosystem would like to use our tool too, I'm about sure he will be happy to use pip-init "out of the box" with no other installation requirement.

Pytest is definitely going to the opt-ins! We need it.

**Comment by Nolent** [comment]
Does black check if a code is valid ? If not i would not consider it as a linter and create a specific category for formatter.

**Comment by LeMinaw** [comment]
Lgtm, edited

**Comment by LeMinaw** [comment]
Should we bring sphinx as opt-in or opt-out?

Opt-out pros:
- promotes usage of a documentation generation tool
- it is a de-facto standard
Opt-in pros:
- Sphinx is heavy
- Small projects probably don't need it

**Comment by Julien00859** [comment]
> Small projects probably don't need it

A project that is not worth a documentation is not worth using a namespace in pypi *change my mind*

**Comment by LeMinaw** [comment]
I don't see why incipyt would be used exclusively in projects meant to be sent to PyPI.
