### ISSUE TITLE
Bootstrap of build tools

### ISSUE THREAD

**Issue by fblanchetNaN** [NotANameServer/incipyt#10]
Regarding https://github.com/NotANameServer/incipyt/wiki/Build-systems many metadata can be given for build tools, the question is then : what `incipyt` does about them ?

I see three different policy:
- [1] Ask to the user (directly through command line options or a prompt input);
- [2] Ignore it;
- [3] Ask to the user but he can let it blank;
- [4] Have a default value and ask the user to confirm or change it;
- [5] Set a predefined value;

Note that we also need variable name for them in our code, let's also discuss them here, I note them `{VARIABLE}` here.

Let's review each metadata:
- `name` [mandatory], imo only [1] is possible here, `{NAME}` or `{PROJECT_NAME}` ?;
- `version` [mandatory], [1], [4] or [5], `{VERSION}` ?
- `authors.email`, [1], [2] or [3], `{AUTHOR_EMAIL}` ?
- `authors.name`, [1], [2] or [3], `{AUTHOR_NAME}` ?
- `classifiers`, [2] or [5] ? If [5], which ones ?
- `dependencies`, imo we cannot really do anything for it, so [2], 
- `description`, [3] `{DESCRIPTION}` ?
- `maintainers.email`, [2], [3] or [4], `{MAINTAINER_EMAIL}` ? For policy [4], the default value could be `{AUTHOR_EMAIL}`.
- `maintainers.name`, [2], [3] or [4], `{MAINTAINER_NAME}` ? For policy [4], the default value could be `{AUTHOR_NAME}`.
- `optional-dependencies.dev`, imo this one should be populated by any tools that need it, e.g. `pytest` would add itself here, in #9 I setup a hook system for that.
- `readme`, [5] and fill `README.md` with `{DESCRIPTION}` ?
- `requires-python`, [2], [4] or [5] ?
- `urls.*`, imo [2] is the best here, it's too early to ask the user for them.

For `setuptools`, two more things are needed:
- `options.package`, it should correspond to the source folder, do we deal with the case multiple packages in one project or not ? If not, `name`, `options.package` and source folder are identical up to a normalization policy. I think we can start by restricting ourselves with this "simple" case.
- `options.package_data` imo the simplest is to decide a name for data folder, and get stick with it : `{SRC_FOLDER}/data` or `{SRC_FOLDER}/assets` ? But [3] or [4] is also possible.

Then after all files are created, what `incipyt` should do:
- Install the package in developer mode in the virtual environment ?
- Build the project ?

**Comment by Julien00859** [comment]
I like how sphinx works, when you bootstrap the documentation it prompts you for a ton of settings but there are just a very few ones that are mandatory.

When the option is mandatory, it prompts you without suggestion and you cannot leave the option empty.

When the option is mandatory/useful (version, author) but can be determined from the environment (author can be determined from `git config user.{name|email}`) or there is a pretty obvious default value (version can be `0.0.0`), it prompts you but suggest a default value that is pick if you leave the field empty.

When the option is rather "opt-in" (classifiers, python-requires), it doesn't prompt but write a no-op setting in the output configuration. We could inject some of those values in the `pyproject.toml` commented. With or without default value suggested.

---

I continue to stick with my idea of a wizard:

```
$ incipyt
Name: foo                                                       # mandatory
Description []:                                                 # optionnal
Author [Julien Castiaux]:                                       # mandatory with suggested default $(git config author.name)
Email [julien.castiaux at example.com]:                         # mandatory with suggested default $(git config author.email)
Version [0.0.0]:                                                # mandatory with suggested default (0.0.0)
Home page [pypi.org/foo]: <space>                               # optionnal with suggested default
Repository []: github.com/julien/foo                            # optionnal
Issues [github.com/julien/foo/issues]:                          # optionnal with suggested default if home page was set and is a repository
Documentation [github.com/julien/foo/wiki]: foo.readthedocs.io  # optionnal with suggested default if home page was set and is a repository
Requires-python [3]: 3.6                                        # optionnal with suggested default

Project foo have been bootstraped

$ cat pyproject.toml
[build-system]
requires = [
  "setuptools",
  "wheel",
]
build-backend = "setuptools.build_meta"
$ cat setup.cfg
[metadata]
name = foo
version = 0.0.0
description = 
long_description = file: README.md
long_description_content_type = text/markdown
author_email = Julien Castiaux <${AUTHOR_EMAIL}>
#maintainer_email =
#url =
project_urls =
    Repository = github.com/julien/foo
    Issues = github.com/julien/foo/issues
    Documentation = github.com/julien/foo/wiki
classifiers =  # https://pypi.org/classifiers/
    Programming Language :: Python
    Programming Language :: Python :: 3
[options]
packages = foo
python_requires = >=3.6

[options.package_data]
* = data/*```

I was lazy and decided my wizard in this example was only supporting a very few options and was using setuptools.
