### ISSUE TITLE
Default logging level

### ISSUE THREAD

**Issue by fblanchetNaN** [NotANameServer/incipyt#22]
IMO default level should be WARNING. The verbosity could be increased via cumulative `-v` options and decreased via cumulative `-s` options. Duty for another PR, IMO INFO is fine for now.

_Originally posted by @Julien00859 in https://github.com/NotANameServer/incipyt/pull/15#discussion_r638690879_

**Comment by Julien00859** [comment]
As inspiration, here's my own logging configuration boilerplates https://github.com/readthedocs-fr/aioircd/blob/master/aioircd.py#L21-L59

**Comment by Julien00859** [comment]
up
