### ISSUE TITLE
Build system and virtual environment tool for incipyt

### ISSUE THREAD

**Issue by fblanchetNaN** [NotANameServer/incipyt#3]
We need to define witch build system we want to use for incipyt itself and also the recommanded tool for virtual environement for incipyt developers (as those tools don't imply anything to commit, actually you can use whatever you want).

Regarding https://github.com/NotANameServer/pip-init/wiki/Build-systems I think flit is a good candidate:
- It's a tool dedicated to build package, and only that (compared to pdm and poetry);
- It supports PEP 517 and PEP 621;
- It's configured by a single file pyproject.toml (compared to setuptools);

About virtual environment, actually the only one that supports multiple virtual environment (regardless major/minor version of the package) is the builtin venv, imo it's the best candidate for that.

Disregarding the build system, we need to choose metadata for incipyt:
```
[project]
name = "incipyt"
version = "0.0.1"
description = Someone to write a nice short description here and README.md ?
readme = "README.md"
authors = [
  {name = "TO-DO", email = "TO-DO"}
]
maintainers = [
  {name = "TO-DO", email = "TO-DO"}
]
requires-python = ">=3.6"
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Intended Audience :: Developers",
  "Topic :: Software Development",
  "Topic :: Software Development :: Code Generators"
]

[project.urls]
homepage = "https://github.com/NotANameServer/pip-init"
documentation = "https://github.com/NotANameServer/pip-init" #Temporary
repository = "https://github.com/NotANameServer/pip-init"
```
Two questions:
- Are all those trove classifiers (see https://pypi.org/classifiers/) relevant ? Others to add ?
- What names/email do we use ?

**Comment by Julien00859** [comment]
I would change the documentation to the wiki :)

I would only list `Prog Lang :: Py :: 3 :: Only` and I'll argue that we use the python version that is currently in use in debian stable

**Comment by Julien00859** [comment]
description: incipyt is a command-line tool that bootstraps a python project

**Comment by Nolent** [comment]
`Environment :: Console` could be good too
